name: Pull request workflow

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [lint, test, build]
    steps:
      - uses: actions/checkout@v5

      - uses: jetify-com/devbox-install-action@v0.14.0
        with:
          enable-cache: true

      - run: devbox run -- make ${{ matrix.target }}
